--SELECT DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)

--SELECT DATEADD(Month,1,(DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)))

--SELECT DATEADD(DAY, -1,(DATEADD(Month,1,(DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)))))

SELECT DATEDIFF(DAY, GETDATE(), (DATEADD(DAY, -1,(DATEADD(Month,1,(DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)))))))
